INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (14, 'Tangelo IPA', 1, 'Big pine flavor with aromas of citrus and stone fruits. Clean, dry finish', 6.6, 'https://gdurl.com/mIsp');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (14, 'Cosmic Coaco', 2, 'Brewed with cocoa nibs, aged on oak spirals, spiced with Mexican vanilla for a nice milky finish', 6.6, 'https://gdurl.com/Qzok');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (14, 'Pecan Brown Ale', 3, 'Full-bodied American, smooth brown ale brewed with candied pecans, brown sugar, and lactose.', 6.4, 'https://gdurl.com/Znkl');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (14, 'Irish Dry Stout', 2, 'Traditional, low gravity Irish stout brewed with barley flakes for added body. Roasted aroma with a little sweet malt. Finishes dry with chocolate undertones.', 4.2, 'https://gdurl.com/IoEK');

INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (15, 'Head Hunter', 1, 'Head Hunter is an aggressively dry-hopped, West Coast-style IPA with a huge hop display of pine, grapefruit, citrus and pineapple. A brew for those who truly love their hops! Award-Winning.', 7.5, 'https://gdurl.com/l5Pv');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (15, 'Goggle Fogger', 3, 'The "Hefe" prefix means "with yeast" which gives this unfiltered wheat beer a somewhat cloudy or "foggy" appearance. Light aromas of wheat, bubblegum, clove and spice.', 5, 'https://gdurl.com/9KHj');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (15, 'Up In Smoke', 5, 'A robust porter brewed with malted barley and coffee. Smoked over Adler wood. Finishes nice and dry.', 9, 'https://gdurl.com/P1m8');

INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (16, 'Progress', 4, 'Great American Beer Festival Award Winning Brew! Inspired by the Pilsners of the Rhine region, this lager is a tribute to the spicy, crisp and clean character of German noble hops and has just the right malt body to balance.', 4, 'https://gdurl.com/mRIm');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (16, 'Midnight Vorlauf', 5, 'This beer is brewed with brown, chocolate and crystalized malts then blended with rich and clean cold brewed coffee, yielding a smooth, robust character of a dark Porter.', 6, 'https://gdurl.com/N5R6');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (16, 'CitraMax', 1, 'A bold floral and fruity hop profile courtesy of Centennial and Citra hops. Flaked rye and crystal malt provide a nice balance and round mouthfeel, obscuring a high ABV punch.', 9.2, 'https://gdurl.com/nql8');
 
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (17, 'Edmund Fitzgerald', 5, 'Brewed in memory of the sunken freighter with rich, roasted barley with bittersweet chocolate-coffee notes.', 6, 'https://gdurl.com/QfQG');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (17, 'Dortmunder', 6, 'A smooth, award-winning (and deceptively unassuming) balance of sweet malt and dry hop flavors. Smooth. Balanced. Charmingly unpretentious.' , 5.8, 'https://gdurl.com/d9mC');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (17, 'Chillwave', 1, 'Earthy, tropical Mosaic hops ride frontside here, followed by a deft cutback of sweet honey malt.', 9.1, 'https://gdurl.com/f31M');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (17, 'Blackout Stout', 2, 'Pitch-dark and rich Imperial Stout. Kindled with black malt and roasted barley. Illuminated by flickers of bitter hops.', 9.9, 'https://gdurl.com/E-VI');

INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (18, 'Peanut Butter Cup', 2, 'this stout has layers of chocolate, mocha and caramel all heightened by the heavy handed addition of locally roasted coffee.', 5.5, 'https://gdurl.com/XZ-X');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (18, 'Community', 4, 'Simple, bready malts and a healthy dose of American and European Noble hops combine in a beer that truly anyone can enjoy.', 5, 'https://gdurl.com/sQiR');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (18, 'Nut Smasher', 2, 'Award-winning Imperial Stout. Seven types of malts. Infused with fresh-roasted coffee, chocolate and peanut butter. Rich, ebony pour with light brown head.', 11.5, 'https://gdurl.com/TSas');

INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (19, 'Siberian Night', 2, 'Very dark, rich, creamy and full-bodied Russian Imperial Stout whose complex character from generous amounts of roasted, toasted, and caramel malts.', 8.9, 'https://gdurl.com/XcLc');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (19, 'Old LegHumper', 5, 'This dark brown, robust porter is full bodied with a deep roasted, silky smooth, malty sweet taste.', 5.5, 'https://gdurl.com/Gt_d');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (19, 'Citra Dog', 1, 'You’ll find evidence of tangerine, grapefruit, orange and mango in the flavor and aroma from the multiple addition of a single hop variety, Citra.', 6.8, 'https://gdurl.com/S1Rk');

INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (20,'BORIS Imperial Stout', 2, 'This Bodacious Oatmeal Russian Imperial Stout will crush you like no other! This is the grand-daddy of all stout styles, with an intensely deep roasted and full bodied flavor. A robust hop character adds a refreshing balance.', 9.4, 'https://gdurl.com/NxSy');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (20,'Silk Porter', 5, 'Dark, robust and silky-smooth, with many flavors of roasted, toasted and caramel malts. Porter is an old-world beer style that fueled the industrial revolution.', 6.5, 'https://doc-0s-ak-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ln5c2rjdtsi5eunjdkqkh1rlp94pabs9/1555524000000/07855601184608224584/*/16jpPF8vDeclNnMQepLNkP83JuKbiJTNK ');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (20,'Gangster Frog IPA', 1, 'Crisp and satisfying American I.P.A. with a skillfully assertive American hop aroma & flavor. Bright spicy citrus hop character up front, with a distinct orange & tropical fruit bouquet to add a welcome complexity & strike the perfect balance.', 7.5, 'https://doc-0s-ak-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/ln5c2rjdtsi5eunjdkqkh1rlp94pabs9/1555524000000/07855601184608224584/*/16jpPF8vDeclNnMQepLNkP83JuKbiJTNK');

INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (21,'Dog Pound Brown', 3, 'Traditional brown ale enlivened with nutty biscuit and mild chocolate aromas.', 6.2, 'https://doc-0s-ak-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/brh918c91gqdk5ncm768doa0ksonl64h/1555531200000/07855601184608224584/*/16jpPF8vDeclNnMQepLNkP83JuKbiJTNK');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (21,'Cuyahoga Porter', 5, 'Robust and roasted. Slight sweetness a touch of chocolate', 5.8, 'https://doc-0s-ak-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/brh918c91gqdk5ncm768doa0ksonl64h/1555531200000/07855601184608224584/*/16jpPF8vDeclNnMQepLNkP83JuKbiJTNK');
INSERT INTO beer (brewery_id, beer_name, beer_type, beer_description, abv, image) VALUES (21,'Buck IPA', 1, 'Deep piney, resinous flavor augmented by sweet melon.', 7.2, 'https://doc-0s-ak-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/brh918c91gqdk5ncm768doa0ksonl64h/1555531200000/07855601184608224584/*/16jpPF8vDeclNnMQepLNkP83JuKbiJTNK');

